name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js

        uses: actions/setup-node@v1

        with:
          node-version: "16"
      - name: npm install

        run: |
          make install

      - name: Run linter

        run: |
          make lint
